#ifndef FANORONA_CONFIG_H
#define FANORONA_CONFIG_H

// Tailles par défaut centralisées
#define DEFAULT_MAIN_WINDOW_WIDTH  800
#define DEFAULT_MAIN_WINDOW_HEIGHT 600
#define DEFAULT_MINI_WINDOW_WIDTH  700
#define DEFAULT_MINI_WINDOW_HEIGHT 500

#endif // FANORONA_CONFIG_H